name: CI
on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      # СТАВИМ зависимости ТОЛЬКО в apps/web
      - name: Install deps (apps/web only)
        working-directory: apps/web
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi

      - name: Typecheck
        working-directory: apps/web
        run: npx -y -p typescript tsc -p tsconfig.ci.json --noEmit

      - name: ESLint
        working-directory: apps/web
        run: npm run lint

      - name: Build
        working-directory: apps/web
        run: npm run build
